[package]
name = "tlsf"
version = "0.1.0"
authors = ["Steven Le Rouzic <steven.lerouzic@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fnd = { path = "../fnd" }